---
include:
  # 왼쪽 키보드 - 일반 사용 펌웨어
  - board: eyelash_sofle_left
    shield: nice_view
    artifact-name: sofle_left_main
  
  # 오른쪽 키보드 - 일반 사용 펌웨어
  - board: eyelash_sofle_right
    shield: nice_view_custom
    artifact-name: sofle_right_main
  
  # 왼쪽 키보드 - ZMK Studio 설정용 (실시간 키맵 편집)
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: sofle_left_studio
  
  # 왼쪽 키보드 - 설정 초기화용 (문제 발생 시 사용)
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: sofle_left_settings_reset
